### ISSUE TITLE
More detailed usage instructions?

### ISSUE THREAD

**Issue by junaidlodhi22** [vvvirani/flutter_amazon_payfort#1]
Hi thank you for working on this
we want to implement this package.
can you update the **Readme** with more detailed instructions
We tried an example package but it is sending me a Technical problem. It seems fine as we have not put our credentials
Can you upload more instructions?

**Comment by vvvirani** [comment]
Sure, I can add more details for about usage instructions.

Can you provide your issue for implementation related? So i will update on ReadMe file.

**Comment by SEPLBipin** [comment]
Hello There,
We want to implement this package.
but get the initialization null error, i have integrated all initialization instruction but the same error. give me proper soluation as soon as posible. thank you.

**Comment by vvvirani** [comment]
Can your share your example? I need to check it.
