### ISSUE TITLE
Payment is not working in Android - "Something went wrong, But we are on it."

### ISSUE THREAD

**Issue by mohit-gaur05** [vvvirani/flutter_amazon_payfort#10]
**Android** - Credit/Debit Card payment is showing error screen in debug mode, not getting any response in onFailed or onSucceeded callback.
![MicrosoftTeams-image (17)](https://github.com/vvvirani/flutter_amazon_payfort/assets/97610352/06a8aa77-aa42-4ee4-a6a5-107efe6f680c)
**Android** - Technical Error in release mode.
Working perfectly in iOS both debug and release.

**Comment by vvvirani** [comment]
Done
