### ISSUE TITLE
Flutter amazon_payfort :Invalid card number

### ISSUE THREAD

**Issue by goddev99** [vvvirani/flutter_amazon_payfort#12]
I tried to run the example of amazon_payfort package. version:1.0.1
I set the payment configuration like this
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/26c5d3b3-8982-4bbd-b573-8170f0daacc3)
After input payment card information, I am getting 00016 response.
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/2ffa6bab-df17-4c3a-8214-e63e071f4f72)
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/15165fcf-f4dc-4682-bc2a-71a71b806e39)

I can't find the cause.
Please help me to fix this error.
Best regards.

**Comment by vvvirani** [comment]
Hello @goddev99  How I can help you?

Please confirm once you are trying with sandbox.

**Comment by devz097** [comment]
I used the test sandbox 4111 1111 1111 1111 and worked correctly.
But I am getting technical error on iOS.
response code: 13006
response message: technical problem.

Can you help me to fix this issue on iOS?
Thank you.

**Comment by vvvirani** [comment]
Hello @devz097 
Use the latest version.
