### ISSUE TITLE
Flutter_amazon_payfort: NSLocalizedDescription=No entitlement for merchant identifier: xxxxxxx

### ISSUE THREAD

**Issue by goddev99** [vvvirani/flutter_amazon_payfort#14]
when click applepay, I am getting this error

[General] Failed to present in-app payment interface: Error Domain=PKPassKitErrorDomain Code=4 “No entitlement for merchant identifier: 01f19a33” UserInfo={NSLocalizedDescription=No entitlement for merchant identifier: 01f19a33}
2023-11-05 08:27:32.081341+0800 Runner[53987:3815356] [General] Connection to remote alert view service failed

I created merchantID, payment processing certificate and imported .p12 file on the Apple Pay Setting.
But I am getting the error continue.
What is the setting that I didn't set?

Please help me. Thank you.

**Comment by vvvirani** [comment]
Hello @goddev99 

Check once. Is `Apple Play` capability added in Xcode with merchant identifier?

<img width="762" alt="Screenshot 2023-11-22 at 10 01 27 AM" src="https://github.com/vvvirani/flutter_amazon_payfort/assets/55572605/95b5c4e3-53f2-487d-95e0-86c51ecff358">

**Comment by goddev99** [comment]
Yes it was added correctly.
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/d91abbba-5db6-4ff1-9e9c-dd545d6e357e)

**Comment by vvvirani** [comment]
@goddev99 Is the Apple Pay payment certificate verified from the PayFort console?

**Comment by goddev99** [comment]
I am not a owner of account.
Owner created sandbox account and allowed to check payment security setting.
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/978404d4-316e-4a48-a269-4654606f45b1)

This is a security setting page.
![image](https://github.com/vvvirani/flutter_amazon_payfort/assets/73145400/39b1ef1a-7234-4cf7-9bd2-84b936c14f0d)
I uploaded .p12 file according to the requirements.
I don't know what I do more.
Please help me.
Thank you.

**Comment by vvvirani** [comment]
Can you share your example project and the test payfort console?
I will fix it.

**Comment by goddev99** [comment]
I fixed the error updating apple merchantID

**Comment by vvvirani** [comment]
Good job
