### ISSUE TITLE
Always get response_code": "00006 with response_message": "Technical problem" after clicking apple pay button.

### ISSUE THREAD

**Issue by goddev99** [vvvirani/flutter_amazon_payfort#15]
I tried to use amazon_payfort version 1.0.3
when clicking apple pay button, I am getting technical problem(0006)
Request Payfort :[“order_description”: “Test Order”, “token_name”: “”, “phone_number”: “”, “merchant_reference”: “cbda6d4e-e89b-494a-84b6-39bb5c4be0e9", “digital_wallet”: “APPLE_PAY”, “payment_option”: “”, “currency”: “SAR”, “customer_name”: “Test Customer”, “sdk_token”: “”, “command”: “PURCHASE”, “amount”: “100000", “customer_email”: “[test@customer.com](mailto:test@customer.com)”, “customer_ip”: “192.168.10.75", “language”: “en”]
failed: technical problem - [“order_description”: “Test Order”, “token_name”: “”, “phone_number”: “”, “merchant_reference”: “cbda6d4e-e89b-494a-84b6-39bb5c4be0e9", “digital_wallet”: “APPLE_PAY”, “payment_option”: “”, “currency”: “SAR”, “customer_name”: “Test Customer”, “sdk_token”: “”, “command”: “PURCHASE”, “amount”: “100000", “customer_email”: “[test@customer.com](mailto:test@customer.com)”, “customer_ip”: “192.168.10.75", “language”: “en”] - [“response_code”: “00006", “status”: “00", “response_message”: “technical problem”]

How can I fix this error?

**Comment by vvvirani** [comment]
Where is the sdk_token ?
From package all is working well

please check your configuration and payload details.

Manage apple pay error: https://developer.amazon.com/docs/amazon-pay-api-v2/error-handling.html
