### ISSUE TITLE
payment_option and token_name parameters

### ISSUE THREAD

**Issue by omeramasib** [vvvirani/flutter_amazon_payfort#17]
Hey,

i'm in touch with amazon payment team and they told me that there are some parameters go with null or empty values and that could raise some issue in the production this parameters are (payment_option and token_name) some time it send with null or empty values and that raise issue , so please fix them.

**Comment by vvvirani** [comment]
Hello @omeramasib 

Issue Solved.
Please check https://pub.dev/packages/amazon_payfort version 1.0.7.
