### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by tariqarbi03** [vvvirani/flutter_amazon_payfort#20]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amazon_payfort:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.

     ERROR:C:\............\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.

     ERROR:C:\............\build\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.

**Comment by amr-muhammad-anwar** [comment]
Same issue

**Comment by vvvirani** [comment]
Hello Guys, I have already fixed this issue with the latest version.

Try these steps:
1. `flutter clean`
2. `flutter pub get`
3. `flutter run`

**Comment by tariqarbi03** [comment]
i tried this but its not working for me..
I am using 3.7.0 flutter vesion and compilesdk/target sdk is 34

**Comment by amr-muhammad-anwar** [comment]
still

**Comment by amr-muhammad-anwar** [comment]
Execution failed for task ':amazon_payfort:verifyReleaseResources'.
  > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
  > Android resource linking failed
    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.

    ERROR:D:\\amazon_payfort\intermediates\merged_res\release\values-v34\values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.

**Comment by amr-muhammad-anwar** [comment]
> Hello Guys, I have already fixed this issue with the latest version.
> 
> Try these steps:
> 
> 1. `flutter clean`
> 2. `flutter pub get`
> 3. `flutter run`

any updates ??

**Comment by vvvirani** [comment]
Hello Guys, Give me some time to fix this issue. I will update you soon.

**Comment by tariqarbi03** [comment]
> Hello Guys, Give me some time to fix this issue. I will update you soon.

any update??? i am waiting to release my build ....

**Comment by vvvirani** [comment]
Working on it...

**Comment by vvvirani** [comment]
Hello Guys,

I have checked and found out this issue comes only with the latest Flutter version.

Please user the flutter 3.10.5 version to run the example.

**Comment by amr-muhammad-anwar** [comment]
i cant use 3.10.5 ?

**Comment by vvvirani** [comment]
Successfully uploaded https://pub.dev/packages/amazon_payfort version 1.1.0.

Now no need to downgrade. I have fixed it
