### ISSUE TITLE
apple pay issue

### ISSUE THREAD

**Issue by pioneersDeveloper** [vvvirani/flutter_amazon_payfort#21]
when appears sandbox to pay ... 
onFailed callback return "Something went wrong"

**Comment by vvvirani** [comment]
The simulator does not support Apple Pay. So try with the real device and follow all the steps carefully.

**Comment by pioneersDeveloper** [comment]
I reached out to support, and they suggested using the payment package to authenticate the transaction through the API. Subsequently, I implemented the integration, but the API response_message indicates 'Failed to execute service with response code 00099.

**Comment by vvvirani** [comment]
Please check your integration for Apple Pay. I mean the Apple developer console, Xcode, etc.

**Comment by MostafaSolimanMO** [comment]
@pioneersDeveloper Were you able to solve it?
