### ISSUE TITLE
problem when run on android device 

### ISSUE THREAD

**Issue by M7Moud1** [vvvirani/flutter_amazon_payfort#22]
![Screen Shot 2024-02-12 at 14 55 22](https://github.com/vvvirani/flutter_amazon_payfort/assets/16584525/3af17ba9-d9c1-443b-ba68-e743d157a8a4)

**Comment by vvvirani** [comment]
Hello @M7Moud1 ,

Are you trying run example?

**Comment by M7Moud1** [comment]
> Hello @M7Moud1 ,
> 
> Are you trying run example?

yes, it runs successfully but when add package in project was fail

**Comment by vvvirani** [comment]
Hello @M7Moud1 

Update your Kotlin version to the same as the example.
