### ISSUE TITLE
Customer IP shouldn't be required value in FortRequest

### ISSUE THREAD

**Issue by MostafaSolimanMO** [vvvirani/flutter_amazon_payfort#28]
Refering to [Amazon Docs](https://paymentservices-reference.payfort.com/docs/api/build/index.html#redirection-urls:~:text=name%3D%E2%80%9Cform1%E2%80%9D%3E%20%3C/form%3E-,Authorization/Purchase%20%2D%20Request,-Example%20%2D%20Authorization/Purchase) `Customer IP` is an Optional param but it's required in the [FortRequest model](https://github.com/vvvirani/flutter_amazon_payfort/blob/main/lib/src/models/fort_request.dart)

![image](https://github.com/user-attachments/assets/f858b071-73c4-4eab-8839-bb91b68f21a0)

**Comment by vvvirani** [comment]
@MostafaSolimanMO Ok, I will update it.

**Comment by ahmeddhus** [comment]
`customerName` and `order_description` too.

![Screenshot 2024-08-12 at 3 55 28 PM](https://github.com/user-attachments/assets/b095195c-eb7e-4c9e-9fdf-c17312241bcf)
![Screenshot 2024-08-12 at 3 56 13 PM](https://github.com/user-attachments/assets/a604713f-bd68-4417-ad19-135006aa4184)

**Comment by vvvirani** [comment]
Done
