### ISSUE TITLE
Feature Request: Allow Command Customization (AUTHORIZATION instead of PURCHASE)

### ISSUE THREAD

**Issue by MostafaSolimanMO** [vvvirani/flutter_amazon_payfort#31]
In our project, we need the ability to change the command from `PURCHASE` to `AUTHORIZATION`. However, the current implementation doesn't support this flexibility, and we were unable to override the default command.

It would be great to add support for customizing the command type to accommodate different use cases, such as using `AUTHORIZATION` instead of `PURCHASE`.

Thank you for considering this enhancement!

**Comment by vvvirani** [comment]
Ok, sure, I will update you soon

**Comment by ahmeddhus** [comment]
Hi @vvvirani, I've submitted a PR to address feature request #33. Please check it out!

**Comment by vvvirani** [comment]
Thanks. I will review and merge.Sent from my iPhoneOn 7 Nov 2024, at 11:45 PM, Ahmed Hussein ***@***.***> wrote:﻿
Hi @vvvirani, I've submitted a PR to address feature request #33. Please check it out!
