### ISSUE TITLE
Api Error not getting Sdk Token.

### ISSUE THREAD

**Issue by Sujayvayuz07** [vvvirani/flutter_amazon_payfort#34]
Api - POST https://sbpaymentservices.payfort.com/FortAPI/paymentApi 

Responce -  {"response_code":"00006","service_command":"SDK_TOKEN","device_id":"ca7531e7-a2cf-467e-bc20-79109cb64c5d","response_message":"Technical problem","merchant_identifier":"****** *******","access_code":"**** *********","language":"en","status":"00"

Getting this responce not getting sdkTokenResponse.sdkToken from Api.

What is The Solution.

Kinldy help me.
Contact - sujay.trivedi@vayuz.com

**Comment by Sujayvayuz07** [comment]
@vvvirani  please reply its urgent for me !!

**Comment by vvvirani** [comment]
Hello, thank you for contacting me.

Please contact the support team. It's a console-side issue. Something is
missing from the console.
