### ISSUE TITLE
payment page of example app not displaying in release mode

### ISSUE THREAD

**Issue by salahvk** [vvvirani/flutter_amazon_payfort#6]
Hi , This is a good package, Any way after integaration the payment page is not displaying in release mode, is it due to merchant id and access code that i used. it's what you provided in the example app

**Comment by vvvirani** [comment]
Can you share you functionality video and example code? So I can review and fix it.

**Comment by salahvk** [comment]
https://drive.google.com/file/d/1312QfEy6hbDUv4W0nGEa2nF9bREW5OYY/view?usp=share_link While debugging (No problem )

https://drive.google.com/file/d/19Dqm_5A1dTkna4lRW6zcoZ7W93EbjPby/view?usp=share_link In release Mode (Payment page not displaying)

**Comment by salahvk** [comment]
import 'package:amazon_payfort/amazon_payfort.dart';

class FortConstants {
  FortConstants._();

  static const FortEnvironment environment = FortEnvironment.test;
  static const String merchantIdentifier = 'a22cf652';

  // For Debit/Credit Card
  static const String accessCode = 'zhV548hfhLbKb69Yf3h0';
  static const String shaType = 'SHA-256';
  static const String shaRequestPhrase = '87cpfpOPZY6fn0GLn7fY98?}';

  // For Apple Pay
  static const String applePayAccessCode = '9ogSafW0OJ4shiPF6KC0';
  static const String applePayShaType = 'SHA-256';
  static const String applePayShaRequestPhrase = '15uQZibFMBqxPrZEKgjwOm_]';

  static const String applePayMerchantId = 'merchant.d.dooskarting.com';
}

**Comment by salahvk** [comment]
I used the same constants for testing,
will the problem get solved if i change merchantId and accessCode

**Comment by vvvirani** [comment]
Ok i will check it

**Comment by vvvirani** [comment]
Hello @salahvk 

Need more time to fix it. Facing arm64 has not found an issue. I will notify you on fixed

**Comment by Mahmoudmsa** [comment]
Hello @vvvirani, first of all it is a great package and works fine on test, but we face the same problem on release either on  credit card on android or Apple Pay on IOS despite credit card works on IOS and screen open 

Did you fix this issue?, please advise how can we fix

**Comment by Hossamattia028** [comment]
Hey any news about this problem @vvvirani  ?

**Comment by Hossamattia028** [comment]
any news for this issue @Mahmoudmsa @salahvk ?
